"""Build a beautiful HTML email digest of events."""

from datetime import datetime
from urllib.parse import quote
import config

CATEGORY_EMOJI = {
    "music": "🎵",
    "sports": "⚽",
    "arts": "🎭",
    "family": "👨‍👩‍👧‍👦",
    "outdoor": "🌿",
    "comedy": "😂",
    "food": "🍽️",
    "other": "✨",
}

CATEGORY_COLOR = {
    "music": "#7c3aed",
    "sports": "#0369a1",
    "arts": "#b45309",
    "family": "#15803d",
    "outdoor": "#166534",
    "comedy": "#c2410c",
    "food": "#9f1239",
    "other": "#475569",
}


def build_email(events: list[dict], start_date: datetime, end_date: datetime) -> str:
    date_range = f"{start_date.strftime('%B %d')} – {end_date.strftime('%B %d, %Y')}"
    event_cards = "\n".join(_build_card(e, i + 1) for i, e in enumerate(events))

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fun Things This Week</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Segoe UI',Arial,sans-serif;">

<!-- Wrapper -->
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:24px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

  <!-- Header -->
  <tr><td style="background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%);border-radius:12px 12px 0 0;padding:32px 32px 24px;text-align:center;">
    <div style="font-size:36px;margin-bottom:8px;">🎉</div>
    <h1 style="margin:0;color:#ffffff;font-size:28px;font-weight:700;letter-spacing:-0.5px;">Fun Things This Week</h1>
    <p style="margin:8px 0 0;color:#93c5fd;font-size:15px;">{date_range} &nbsp;·&nbsp; DC / MD / VA</p>
  </td></tr>

  <!-- Intro bar -->
  <tr><td style="background:#1d4ed8;padding:12px 32px;">
    <p style="margin:0;color:#dbeafe;font-size:13px;text-align:center;">
      Top {len(events)} picks for the Squillaro family &nbsp;·&nbsp;
      Hit <strong>Love it</strong> or <strong>Pass</strong> on each event — your votes make next week's list smarter!
    </p>
  </td></tr>

  <!-- Events -->
  <tr><td style="background:#ffffff;padding:8px 0;">
    {event_cards}
  </td></tr>

  <!-- Footer -->
  <tr><td style="background:#f8fafc;border-radius:0 0 12px 12px;border-top:1px solid #e2e8f0;padding:24px 32px;text-align:center;">
    <p style="margin:0 0 8px;color:#64748b;font-size:12px;">
      Generated by <strong>Fun Things</strong> &nbsp;·&nbsp; Running on GitHub Actions
    </p>
    <p style="margin:0;color:#94a3b8;font-size:11px;">
      Votes are recorded securely. Each click opens a quick confirmation page.
    </p>
  </td></tr>

</table>
</td></tr>
</table>

</body>
</html>"""


def _build_card(event: dict, rank: int) -> str:
    category = event.get("category", "other")
    emoji = CATEGORY_EMOJI.get(category, "✨")
    color = CATEGORY_COLOR.get(category, "#475569")

    title = _esc(event.get("title", "Untitled Event"))
    venue = _esc(event.get("venue", ""))
    city = _esc(event.get("city", ""))
    state = _esc(event.get("state", ""))
    location = ", ".join(filter(None, [venue, city, state]))
    description = _esc((event.get("description") or "")[:200])
    if len(event.get("description") or "") > 200:
        description += "…"

    event_url = event.get("url", "#")
    image_url = event.get("image_url", "")
    source = event.get("source", "")
    category_label = category.replace("_", " ").title()

    # Date/time
    date: datetime = event["date"]
    date_str = date.strftime("%A, %B %-d")
    time_str = date.strftime("%-I:%M %p") if date.hour != 0 else "Time TBD"

    # Price
    price_min = event.get("price_min")
    price_max = event.get("price_max")
    if price_min == 0.0:
        price_str = "FREE"
        price_color = "#15803d"
    elif price_min is not None:
        price_str = f"${price_min:.0f}" if price_min == price_max else f"${price_min:.0f} – ${price_max:.0f}"
        price_color = "#475569"
    else:
        price_str = "Price TBD"
        price_color = "#94a3b8"

    # Tags
    tags_html = ""
    for tag in event.get("tags", []):
        tag_label = tag.replace("-", " ").title()
        tags_html += f'<span style="display:inline-block;background:#f0fdf4;color:#15803d;border:1px solid #bbf7d0;border-radius:99px;padding:2px 10px;font-size:11px;margin:2px 4px 2px 0;">{tag_label}</span>'

    # Vote links
    up_url, down_url = _vote_urls(event)
    vote_section = _build_vote_buttons(up_url, down_url)

    # Image row
    image_row = ""
    if image_url:
        image_row = f"""
    <tr><td style="padding:0;">
      <a href="{event_url}" target="_blank">
        <img src="{image_url}" width="600" alt="{title}"
          style="width:100%;max-height:220px;object-fit:cover;display:block;border:none;">
      </a>
    </td></tr>"""

    return f"""
  <!-- Event {rank}: {title} -->
  <table width="100%" cellpadding="0" cellspacing="0" style="border-bottom:1px solid #f1f5f9;">
    {image_row}
    <tr><td style="padding:20px 32px 4px;">
      <!-- Category badge + rank -->
      <table cellpadding="0" cellspacing="0">
        <tr>
          <td style="background:{color};color:#fff;border-radius:99px;padding:3px 12px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;">
            {emoji} {category_label}
          </td>
          <td style="padding-left:10px;color:#94a3b8;font-size:12px;">#{rank}</td>
        </tr>
      </table>
    </td></tr>

    <!-- Title -->
    <tr><td style="padding:8px 32px 4px;">
      <a href="{event_url}" target="_blank"
         style="text-decoration:none;color:#0f172a;font-size:20px;font-weight:700;line-height:1.3;">
        {title}
      </a>
    </td></tr>

    <!-- Date / Location / Price -->
    <tr><td style="padding:4px 32px 8px;">
      <table cellpadding="0" cellspacing="0">
        <tr>
          <td style="color:#475569;font-size:14px;padding-right:20px;">
            📅 <strong>{date_str}</strong> &nbsp;·&nbsp; {time_str}
          </td>
        </tr>
        <tr>
          <td style="color:#475569;font-size:13px;padding-top:3px;">
            📍 {location}
          </td>
        </tr>
        <tr>
          <td style="padding-top:3px;">
            <span style="color:{price_color};font-size:14px;font-weight:600;">💰 {price_str}</span>
            &nbsp;&nbsp;
            <span style="color:#94a3b8;font-size:11px;">via {source}</span>
          </td>
        </tr>
      </table>
    </td></tr>

    <!-- Description -->
    {"<tr><td style='padding:0 32px 8px;color:#64748b;font-size:13px;line-height:1.5;'>" + description + "</td></tr>" if description else ""}

    <!-- Tags -->
    {"<tr><td style='padding:0 28px 8px;'>" + tags_html + "</td></tr>" if tags_html else ""}

    <!-- Vote buttons -->
    <tr><td style="padding:4px 32px 20px;">
      {vote_section}
    </td></tr>

  </table>"""


def _vote_urls(event: dict) -> tuple[str, str]:
    """Build up/down vote URLs pointing at GitHub Pages."""
    base = config.VOTE_PAGE_URL or "https://example.github.io/fun-things/vote/"
    eid = quote(event.get("id", ""), safe="")
    title = quote(event.get("title", "")[:80], safe="")
    cat = quote(event.get("category", "other"), safe="")
    up = f"{base}?id={eid}&v=up&t={title}&c={cat}"
    down = f"{base}?id={eid}&v=down&t={title}&c={cat}"
    return up, down


def _build_vote_buttons(up_url: str, down_url: str) -> str:
    return f"""
<table cellpadding="0" cellspacing="0">
  <tr>
    <td style="padding-right:10px;">
      <a href="{up_url}" target="_blank"
         style="display:inline-block;background:#15803d;color:#ffffff;text-decoration:none;
                border-radius:8px;padding:9px 22px;font-size:14px;font-weight:600;">
        👍&nbsp; Love it
      </a>
    </td>
    <td>
      <a href="{down_url}" target="_blank"
         style="display:inline-block;background:#f1f5f9;color:#475569;text-decoration:none;
                border:1px solid #e2e8f0;border-radius:8px;padding:9px 22px;font-size:14px;font-weight:600;">
        👎&nbsp; Pass
      </a>
    </td>
  </tr>
</table>"""


def _esc(s: str) -> str:
    return (s
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))
